apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.4
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          value: petclinic
        - name: MYSQL_PASSWORD
          value: petclinic
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: petclinic
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP  
  ports:
    - port: 3306
      targetPort: 3306
  selector:
---
---
apiVersion: v1
kind: Secret
metadata:
  name: petmysql-secret-root1
type: kubernetes.io/basic-auth
stringData:
  password: petclinic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 --file docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-petclinic
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spring-petclinic
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 --file docker-compose.yml
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: spring-petclinic
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -javaagent:/opentelemetry-javaagent.jar
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://agent:4317
        - name: OTEL_SERVICE_NAME
          value: pet-clinic
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: db_root_password
          valueFrom:
            secretKeyRef:
              name: petmysql-secret-root1
              key: password
        - name: MYSQL_USER
          value: petclinic
        - name: MYSQL_PASSWORD
          value: petclinic
        - name: MYSQL_DATABASE
          value: petclinic
        image: janajohny/petclinic:v1
        imagePullPolicy: Always
        name: spring-petclinic
        ports:
        - containerPort: 8182
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 --file docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-petclinic
  name: spring-petclinic
spec:
  ports:
  - name: spring-petclinic
    port: 8182
    targetPort: 8182
    nodePort: 30914
  type: NodePort
  selector:
    io.kompose.service: spring-petclinic